services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_STRAPI_API_URL=http://backend:1338
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1338:1338"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/.tmp:/app/.tmp
      # Mount your existing local Strapi SQLite database
      - ./backend/src/database:/app/src/database
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=./src/database/data.db
